drop table if exists bookmarks_table;

create table bookmarks_table (
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url text NOT NULL,
    description text NOT NULL,
    rating INTEGER NOT NULL
);

insert into bookmarks_table(title, url, description, rating)
values
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4),
( 'Thinkful Engineering Flex', 'https://www.thinkful.com/bootcamp/web-development/flexible/', 'Thinkful bootcamp website', 4);